### ISSUE TITLE
Why multiply by coefficient?

### ISSUE THREAD

**Issue by GiilDe** [shaibagon/diffusers_ddim_inversion#1]
Can you explain why you multiply the mean by 0.18215 in this line? 
https://github.com/shaibagon/diffusers_ddim_inversion/blob/66b6ff42a04db6a0df73aa999f0df0a44ddd8223/ddim_inversion.py#L22C32-L22C39 
Thanks

**Comment by shaibagon** [comment]
Hi,
I'm not exactly sure where this constant came from.
You can see similar values in, e.g.,:
https://github.com/omerbt/TokenFlow/blob/master/preprocess.py#L167

I guess this is some kind of scaling const used to train SD. 

And you are right, I should have gotten this kind of "magic numbers" from the proper config files.
