### ISSUE TITLE
The result is bad

### ISSUE THREAD

**Issue by asdcaszc** [shaibagon/diffusers_ddim_inversion#2]
![myplot](https://github.com/shaibagon/diffusers_ddim_inversion/assets/49332920/2971220f-65ca-4e16-9113-798810e90a96)

I run your code but the result is so bad... Do you know why the two images are so different?

Thanks for your sharing and wait your kind reply.

**Comment by Bitterdhg** [comment]
I obtained a satisfactory result by increasing `num_train_timesteps` to 1000 steps.

![image](https://github.com/shaibagon/diffusers_ddim_inversion/assets/86940141/f0f2c246-1669-4544-b9b5-661a48d9f1d8)

**Comment by shaibagon** [comment]
@Bitterdhg thank you for your update!

**Comment by Magicboomliu** [comment]
Sorry, where can I change the num_train_timesteps?

**Comment by shaibagon** [comment]
Simply change this line:
https://github.com/shaibagon/diffusers_ddim_inversion/blob/main/ddim_inversion.py#L60

`num_steps` from 250 to some other number

**Comment by tian-2024** [comment]
> ![myplot](https://private-user-images.githubusercontent.com/49332920/313019805-2971220f-65ca-4e16-9113-798810e90a96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzA4NDUsIm5iZiI6MTczMTU3MDU0NSwicGF0aCI6Ii80OTMzMjkyMC8zMTMwMTk4MDUtMjk3MTIyMGYtNjVjYS00ZTE2LTkxMTMtNzk4ODEwZTkwYTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA3NDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NmQ3Y2QyMGRlNGJjNjEwOTg3M2Q2ZjA2YjVhOGNkZjhmNWVhYzFlMDhiODQxY2JjMTFhZDE4MzQ2Zjk0MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vwFdSw4vGTV3j8NjZCQlrTNpNDzswmN9vZRa0rLeqh0)
> 
> I run your code but the result is so bad... Do you know why the two images are so different?
> 
> Thanks for your sharing and wait your kind reply.

![image](https://github.com/user-attachments/assets/d20e1cb5-0ccc-4bd1-8aa4-9d2d033e8222)

**Comment by x2x5** [comment]
> `num_train_timesteps`

really? I tried 1000 and got error:

IndexError: index 1000 is out of bounds for dimension 0 with size 1000

so I think the max is 999

**Comment by x2x5** [comment]
> ![myplot](https://private-user-images.githubusercontent.com/49332920/313019805-2971220f-65ca-4e16-9113-798810e90a96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzU2NTgsIm5iZiI6MTczMTU3NTM1OCwicGF0aCI6Ii80OTMzMjkyMC8zMTMwMTk4MDUtMjk3MTIyMGYtNjVjYS00ZTE2LTkxMTMtNzk4ODEwZTkwYTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA5MDkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZjZhNDI3Y2VjMGQ3ZjQzYmM1MDU4ZTk1Y2YzYTAyNTQzZTY1ZWFiOWJmYmNiMDAzZTcwMTUyNzI5OTNjNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.R9I4HpaRcKqs6xo3cdPg_9W_ca0t-vHupHJMlNx-4Qk)
> 
> I run your code but the result is so bad... Do you know why the two images are so different?
> 
> Thanks for your sharing and wait your kind reply.

Here are different steps.

small steps number:
![image](https://github.com/user-attachments/assets/40b6aad3-ffc4-4bfc-a101-38f72a66256e)

large steps number (max is 999):
![image](https://github.com/user-attachments/assets/260ee26d-8618-48d4-831c-f416452e12ea)

**Comment by shaibagon** [comment]
@tian-2024  thank you for the detailed results!
